---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: memcached
  namespace: tenant-a-service
  labels:
    acm-app: memcached
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: tenant-a-ch-helm/channel
  name: memcached
  packageFilter:
    version: "5.13.3"
  placement:
    placementRef:
      name: cloud-azure
      namespace: tennant-a
  packageOverrides:
    - packageName: memcached
      packageAlias: memcached
