---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx
  labels:
    acm-app: nginx
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: tenant-a-ch-helm/channel
  name: nginx
  packageFilter:
    version: "9.3.3"
  placement:
    placementRef:
      name: cloud-azure
  packageOverrides:
    - packageName: nginx
      packageAlias: nginx
